[workspace]
members = [
  "budget-app/server",
  "budget-app/client",
  "budget-app/api",
  "binance-bot/shared",
  "binance-bot/client",
  "binance-bot/server",
  "app-model",
  "components",
  "database-table",
]
