[package]
name = "define_api"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "^1"
proc-macro2 = "^1"

[dependencies.syn]
version = "^1"
